-- Phase 8, Box 2: the daily quote.
--
-- A global, read-only list (every signed-in user reads the same rows; nobody can
-- write through the API, so only a migration changes it). The quotes are written
-- for this app, so there is no author: `author` stays null and the app shows no
-- attribution (Minh, 2026-10-06: no real-person attributions unless public
-- domain; none are used). Which quote shows on which day is a pure function of
-- the date (lib/quotes.ts), so the same date gives the same quote to everyone.

create table public.quotes (
  id integer primary key,
  text text not null,
  author text,
  constraint quotes_text_len check (char_length(btrim(text)) between 1 and 200),
  constraint quotes_author_len check (author is null or char_length(btrim(author)) between 1 and 80),
  constraint quotes_text_unique unique (text)
);

alter table public.quotes enable row level security;

create policy "quotes - read"
  on public.quotes for select to authenticated
  using (true);

revoke all on public.quotes from anon, authenticated;
grant select on public.quotes to authenticated;

insert into public.quotes (id, text) values
  (1, 'Small steps still cover the distance.'),
  (2, 'One honest page is worth more than a perfect plan.'),
  (3, 'Start where you are; the warm-up is part of the work.'),
  (4, 'A quiet hour, fully used, can change a whole day.'),
  (5, 'You don''t have to finish today; you only have to begin.'),
  (6, 'Rest is not the opposite of progress. It is how progress holds.'),
  (7, 'The kettle boils without being watched, and so do good habits.'),
  (8, 'Write the line you''re afraid is too plain. It''s usually the true one.'),
  (9, 'Do the next small thing, then the one after that.'),
  (10, 'A tidy corner of the desk is a tidy corner of the mind.'),
  (11, 'Today is allowed to be ordinary.'),
  (12, 'Be as patient with yourself as you are with a slow kettle.'),
  (13, 'Rain on the window, one task on the list: that is plenty.'),
  (14, 'Progress is quieter than panic, and it lasts longer.'),
  (15, 'Ten focused minutes beat an hour of good intentions.'),
  (16, 'Put the phone face down; the world will keep.'),
  (17, 'What you do most days matters more than what you do once.'),
  (18, 'It''s fine to circle back. Circles are how you find the middle.'),
  (19, 'The page doesn''t need you brilliant. It needs you present.'),
  (20, 'A gentle routine is a kind of shelter.'),
  (21, 'Break the big thing into a size you could do before the tea cools.'),
  (22, 'Done and imperfect is a friend; perfect and unstarted is a stranger.'),
  (23, 'Take the break before you need the break.'),
  (24, 'Rest your eyes on something far away; your thoughts will follow.'),
  (25, 'Today''s effort is a letter to next week''s you.'),
  (26, 'A good day can be built from three small yeses.'),
  (27, 'Slow is smooth, and smooth gets there.'),
  (28, 'Let the easy task go first if it opens the door to the hard one.'),
  (29, 'You are allowed to change the plan and keep the goal.'),
  (30, 'Notice what went well. The mind files the rest on its own.'),
  (31, 'Some days the win is simply showing up with the lights on.'),
  (32, 'Make it small enough that you can''t say no.'),
  (33, 'Your attention is the most generous gift you own; spend it on purpose.'),
  (34, 'A cup, a chair, a clear task. Begin.'),
  (35, 'Even a crowded week has a few quiet minutes. Find one.'),
  (36, 'Write down the worry; it weighs less on paper than in your head.'),
  (37, 'Not every day should be a sprint. Walk sometimes.'),
  (38, 'If it''s worth doing, it''s worth doing a little today.'),
  (39, 'Each finished task is a small light left on for tomorrow.'),
  (40, 'You''ve handled every hard day so far. That''s a decent record.'),
  (41, 'Choose the one thing that makes the others easier.'),
  (42, 'The morning doesn''t have to be impressive. It just has to start.'),
  (43, 'Close one tab, finish one thought.'),
  (44, 'Kindness to yourself is not a detour; it''s part of the road.'),
  (45, 'A short walk can untie a long knot.'),
  (46, 'Quiet work leaves a loud result.'),
  (47, 'Leave a little room in the day for whatever turns out to matter.'),
  (48, 'Say no to the extra thing, so yes can mean something.'),
  (49, 'Warm light, steady hands, one page at a time.'),
  (50, 'The hardest part is the first five minutes. Ask only for those.'),
  (51, 'Remember how far the last hard week took you.'),
  (52, 'Dust settles; so will your mind, if you let it sit.'),
  (53, 'Today''s list is a suggestion, not a verdict.'),
  (54, 'Be a good host to your own focus: clear the table, pour something warm.'),
  (55, 'Enough is a real amount. Let yourself reach it.'),
  (56, 'When the day gets loud, shrink the list, not yourself.'),
  (57, 'Write one true sentence. Then another.'),
  (58, 'Rest like it''s part of the job. It is.'),
  (59, 'Tomorrow is a fresh page, and you can stop writing on this one.'),
  (60, 'A little progress, repeated, becomes a different life.'),
  (61, 'Dim the noise, keep the lamp.'),
  (62, 'Let the unfinished things wait their turn; they''re not going anywhere.'),
  (63, 'Courage is often just a very small step taken anyway.'),
  (64, 'Look at what you did today, not only at what''s left.'),
  (65, 'Some of the best ideas arrive while you''re washing a cup.'),
  (66, 'Say what you need. Then give yourself a little of it.'),
  (67, 'The work is allowed to be slow if it''s real.'),
  (68, 'A calm start can carry an entire afternoon.'),
  (69, 'Take the long way home once in a while.'),
  (70, 'You can be tired and still be doing well.'),
  (71, 'When in doubt, tidy the next five minutes.'),
  (72, 'Honest effort, quietly repeated, is hard to beat.'),
  (73, 'Not now doesn''t mean never; it means later, on purpose.'),
  (74, 'Give the hard task your best hour, not your leftover one.'),
  (75, 'A good question is half a plan.'),
  (76, 'Pay attention to what gives you energy, and make more room for it.'),
  (77, 'Let the day end when it ends. Tomorrow has its own light.'),
  (78, 'A habit is just a promise you keep when nobody is checking.'),
  (79, 'The clock measures time; only you can measure care.'),
  (80, 'Anything you do on purpose counts.'),
  (81, 'Sit with the problem a little longer than is comfortable, then walk away and let it simmer.'),
  (82, 'You don''t owe the world a busy face.'),
  (83, 'The small ritual before work is the work''s front door.'),
  (84, 'Write it down, shut the notebook, breathe out.'),
  (85, 'Be curious about your own mind; it has more patience than you think.'),
  (86, 'A finished page is a small act of faith.'),
  (87, 'Not every cloud needs an umbrella; some just need a window seat.'),
  (88, 'What would make the next hour easier? Do that.'),
  (89, 'If you can''t do it well, do it a little. A little is not nothing.'),
  (90, 'Mornings are for beginnings, evenings for gratitude.'),
  (91, 'Trust the slow build; the foundation never looks like much.'),
  (92, 'Don''t wait for the mood. Make the tea and let it arrive.'),
  (93, 'You are the only one who has to live inside today. Make it livable.'),
  (94, 'A good rhythm beats a heroic burst.'),
  (95, 'Today you can be gentle and productive at once.'),
  (96, 'Pick a stopping point before you start; it makes starting easier.'),
  (97, 'The list is long because your life is full, and that is not a flaw.'),
  (98, 'Do it badly first. Polish belongs to the second draft.'),
  (99, 'The glow of one lamp is enough to read by.'),
  (100, 'Hold your goals loosely and your days gently.'),
  (101, 'Every expert once had a day-one that felt like this.'),
  (102, 'Take your time; the best soup was never rushed.'),
  (103, 'Close the loop on one small thing, and feel how light that is.'),
  (104, 'A rainy afternoon is an invitation, not an obstacle.'),
  (105, 'Say thanks to the part of you that kept going.'),
  (106, 'Doubt is a tourist; don''t let it drive.'),
  (107, 'The work will be there tomorrow, and so will you, rested.'),
  (108, 'Little by little, the quiet adds up to something loud.'),
  (109, 'Set the timer, breathe, begin. The rest will follow.'),
  (110, 'Let one good thing be enough for today.'),
  (111, 'Make room for joy on purpose; it won''t always knock.'),
  (112, 'What you practise in small moments grows in large ones.'),
  (113, 'It''s okay to be a beginner every single morning.'),
  (114, 'Take stock gently. Count what you did, not what you didn''t.'),
  (115, 'One focused session is a promise kept to yourself.'),
  (116, 'A warm drink, a cleared desk, a first sentence.'),
  (117, 'Even the longest day is made of ordinary minutes.'),
  (118, 'Ease into it. The hill is climbed one step at a time.'),
  (119, 'You''re allowed to rest before you''re finished.'),
  (120, 'Tonight, put the day down. It did its best, and so did you.');
